name: sw_proyectos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:

  http: ^0.13.3
  flutter:
    sdk: flutter
  provider: ^6.1.2
  build_runner: 2.4.13
  webview_flutter: ^4.2.2
  flutter_spinkit: ^5.2.0


dev_dependencies:


  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
